# -*- coding: utf-8 -*-
"""ChineseToEnglish_ExcelConverter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLNNr2Esa0LC32GU7a9EFc7zKEhWfuyt
"""

!pip install -U deep-translator

import pandas as pd
from deep_translator import GoogleTranslator
import time
import io
from google.colab import files

# prompt: python code to upload a excel file and show its content
uploaded = files.upload()
for fn in uploaded.keys():
  with io.BytesIO(uploaded[fn]) as f:
    df = pd.read_excel(f)

# Start time for performance measurement
start_time = time.time()
# prompt: replace all the NaN with ""
df.fillna('', inplace=True)

# Create a translator object
translator = GoogleTranslator(source='zh-TW', target='en')
# Function to translate a given text to English
def translate_to_english(text):
    if not text:
        return ""  # Handle empty or whitespace-only inputs concisely
    if text.isnumeric():
        return text  # Avoid unnecessary translation for numeric strings
    return translator.translate(text)

# Translate the column names
df.columns = [translate_to_english(header) for header in df.columns]
#Translate the excel file contents
for column in df.columns:
    df[column] = [translate_to_english(str(text)) for text in df[column]]

df.to_excel("translated_sheet.xlsx", index=False)

# End time and calculate duration
end_time = time.time()
duration = end_time - start_time

# Print the time taken for translation and saving
print(f"Translation and saving completed in {duration:.2f} seconds.")